interactiveMode: false
queryCount: 10
outFile: queries.sql
semiAntiJoin: true
limit: true
orderby: true
aggregate: true

targetRteCount: 5
targetCteCount: 1
targetCteRteCount: 3

commonColName: id

targetTables:
  - Table:
      name: dist
      citusType: DISTRIBUTED
      distCol: id
      maxCount: 3
      rowCount: 1000
      nullRate: 0.1
      duplicateRate: 0.1
      columns:
        - Column: 
          name: id
          type: int
  - Table:
      name: ref
      citusType: REFERENCE
      distCol: id
      maxCount: 3
      rowCount: 1000
      nullRate: 0.1
      duplicateRate: 0.1
      columns:
        - Column: 
          name: id
          type: int

targetJoinTypes:
  - INNER
  - LEFT
  - RIGHT
  - FULL

targetRteTypes:
  - RELATION
  - SUBQUERY
  - CTE
  #- TABLEFUNC
  - VALUES

targetRestrictOps: 
  - LT
  - GT
  - EQ

targetAggregateFunctions:
  - min
  - max
  - count

targetRteTableFunctions:
  - generate_series(0,100)
