targetTables:
  - Table:
      name: dist
      citusType: DISTRIBUTED
      distCol: id
      maxCount: 3
      rowCount: 1000
      nullRate: 0.1
      duplicateRate: 0.1
      columns:
        - Column: 
          name: id
          type: int
  - Table:
      name: ref
      citusType: REFERENCE
      distCol: id
      maxCount: 3
      rowCount: 1000
      nullRate: 0.1
      duplicateRate: 0.1
      columns:
        - Column: 
          name: id
          type: int

targetJoinTypes:
  - INNER
  - LEFT
  - RIGHT
  - FULL

targetRteTypes:
  - RELATION
  - SUBQUERY
  - CTE

targetRestrictOps: 
  - LT
  - GT
  - EQ

targetRteCount: 5
targetCteCount: 1
targetCteRteCount: 3
commonColName: id
